### ISSUE TITLE
Finetune scripts

### ISSUE THREAD

**Issue by Pang-Yatian** [kahnchana/svt#10]
Hi,

Thanks for your great work.

May I ask could you please update finetune scripts with the slow-fast inference proposed in this paper.

Looking forward to your updates.

**Comment by kahnchana** [comment]
We exactly follow the procedure in our paper method section. 
1. Obtain two views (slow and fast) with high resolution for space and time respectively
2. Interpolate positional embeddings to fit sequence length (our model code should do this automatically)
3. Fuse the class token features at the end (simply average them)
4. Use this fused vector as the final video embedding

This is the exact procedure that we follow.
