### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by weirukai** [kahnchana/svt#12]
Thanks for sharing your codes. I have some problems loading the training data of UCF101. 1) Where can I find the ucf101_train(test)_split_1_videos.txt? 2) Should I extract RGB frames for each dataset before training?

**Comment by kahnchana** [comment]
Thank you for your interest in our work! 

We use [MMAction2 repo](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ucf101#preparing-ucf-101) for data preparation. We run section 1, 2, and 4 (skip 3 - extract RGB frames / flow). 

Running [section 4](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ucf101#step-4-generate-file-list) will generate those files. 

You do not need to extract RGB frames. The dataloader directly reads from videos.
