### ISSUE TITLE
About pyav performance

### ISSUE THREAD

**Issue by weirukai** [kahnchana/svt#13]
Hello! Thanks for sharing such a good job! When performing pyav decoding, the speed is slow (multi_thread_decode=True). How can I accelerate it ?

**Comment by kahnchana** [comment]
This is an issue we faced too. I have been switching to using [decord](https://github.com/dmlc/decord) in my later work which gives some speed boosts. 

Also, saving the videos resized to 256x256 with dense encoding helps. I followed the procedure on [MMAction2](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics).
