### ISSUE TITLE
hmdb51

### ISSUE THREAD

**Issue by eeehco** [kahnchana/svt#14]
Hello, I read your paper Self supervised Video Transformer published on CVPR and tried to run the code. I found that your training code scripts on GitHub are only kinesics. Do you have any training scripts for hmdb51 or ucf101? If so, I hope you can share them with me. Thank you very much.

**Comment by kahnchana** [comment]
We do not perform any self-supervised training for those datasets. We only perform downstream analysis on them. 

However, you can simply replace the paths and re-use the same dataset classes for these two datasets to the best of my knowledge.
