### ISSUE TITLE
config.MODEL.TWO_STREAM

### ISSUE THREAD

**Issue by kffeng** [kahnchana/svt#15]
Dear team
     Thank you for sharing such a good work. I am very interested in your work. I am a beginner. I have read your paper and code, but there is a parameter（config.MODEL.TWO_STREAM） in the code that I don't understand. Is it input optical flow? If it is set to True, how can it work together config.MODEL.TWO_TOKEN?

**Comment by kahnchana** [comment]
That is part of experimental code that did not give good results. We did not use that setting in our paper. 

It was left as a direction for future research: how to incorporate optical flow into the same system.
