### ISSUE TITLE
About finetuning

### ISSUE THREAD

**Issue by ahnGeo** [kahnchana/svt#18]
Hello!

I want to get detail subscription about finetuning for downstream task on your paper. 

(1) In paper, it said "We replace the projection head over the SVT with a randomly initialized linear layer, initialize the SVT backbone with our pre-trained weights, and train the network end-to-end ~". The repository don't have finetune scripts, so I wonder how you finetune SVT. Is there any script? please let me know.

(2) And, you also said "During both training of linear classifier and fine-tuning of SVT, we sample two clips of varying spatiotemporal resolution from each video.". 'two clips of varying spatiotemporal resolution" means 8X224X224 and 64X96X96, same as slowfast inference?

Thank you for your time!

**Comment by kahnchana** [comment]
Thanks for your interest in our work! 

(1) Yes, we used the [TimesFormer repository](https://github.com/facebookresearch/TimeSformer) for fine-tuning of model. We simply initialize the model with our weights, and follow their same training procedure for fair comparison. 

(2) Yes, that is correct. We sample two clips of resolution (8,224,224) and (64,96,96), pass each through the network, and average the class token embedding of the two. We tried alternate fusing strategies, but they did not improve performance over the averaging baseline.
