### ISSUE TITLE
inconsistency between the paper and the train.sh

### ISSUE THREAD

**Issue by Separius** [kahnchana/svt#2]
Hi, First of all, thank you for providing the training code for your model.
Second, I have found two major inconsistencies between the provided train.sh config and your best model in the paper.
One is that the model is initialized with the pretrained **supervised** weights of a ViT, not an unsupervised one, is that the case also for the numbers in your paper?
and the second one is that the input to the student is two tensors of size 8x224x224 and eight tensors of size 8x96x96, which is again different from the paper.

So my question is, can you provide the config that was used to train your released model?

**Comment by kahnchana** [comment]
Hi, thank you for your interest in our work and for pointing this out. 

Sorry for the confusion; the `train.sh` was simply meant to be a guideline for running training with our code. The training for the given pretrained model follows exactly as mentioned in the paper. 

You can use the `TIMESFORMER.PRETRAINED_MODEL` flag in `train.sh` to set the initialization. It is handled [here](https://github.com/kahnchana/svt/blob/2069edb0c6fdd74e03cdeee5ac8bb7c6c9076f0c/models/timesformer.py#L602). The `DATA.RAND_FR` flag can be used to set the variable frame rate input, which is handled [here](https://github.com/kahnchana/svt/blob/master/datasets/decoder.py#L414). 

We will work on releasing an additional updated `train.sh` soon.
