### ISSUE TITLE
Torchvision.io error when running eval_knn.sh

### ISSUE THREAD

**Issue by ahmad-573** [kahnchana/svt#4]
I am getting this error on initial imports. It goes away by changing pytorch version but then other imports fail.
<img width="586" alt="Screen Shot 2022-06-13 at 12 08 10 AM" src="https://user-images.githubusercontent.com/84383974/173251514-d8002f13-96c2-4705-ba3b-bc0cf64ce1ce.png">

**Comment by kahnchana** [comment]
Updated to work with later pytorch versions.
