### ISSUE TITLE
Error running eval_linear on multiple GPUs

### ISSUE THREAD

**Issue by TalalWasim** [kahnchana/svt#6]
Hi,

When I run eval_linear on multiple GPUs, I keep getting cuda out of memory error. Even with batch_size_per_gpu set to 1, the error is still the same.

It works on single GPU with batch_size_per_gpu set to 16. I am working with the Kinetics400 dataset, I have set inp = inp[0].cuda(non_blocking=True) as suggested in another issue.

Please suggest how to solve this.

Kind regards,
Talal

**Comment by kahnchana** [comment]
We used the [TimesFormer repo](https://github.com/facebookresearch/TimeSformer) for Kinetic400 downstream evaluation (with slight modification for linear eval) since SVT uses the same ViT backbone.
