### ISSUE TITLE
running eval_linear on HMDB51

### ISSUE THREAD

**Issue by AllenPu** [kahnchana/svt#8]
Hi,
  I got the following error like
' Failed to load video from /HMDB51/videos/shoot_ball/WeTheKingsplaying_shoot_ball_u_cm_np1_ba_med_6.avi with error 'utf-8' codec can't decode byte 0x8c in position 65: invalid start byte', it seems the error is from the container = av.open(path), could you plz tell me how to fix that?

**Comment by kahnchana** [comment]
Hi, I am trying to replicate this error. Will try to give an update soon. 

I feel it may be an issue with the `av` library version or the dataset. Are you able to open any video and load frames using `av`?

**Comment by AllenPu** [comment]
yep， when I tried to pretrain over UCF101 it's ok, but when I fine tuned over HMDB51, I got the error, one of the file which caused the error is '/HMDB51/videos/shoot_ball/WeTheKingsplaying_shoot_ball_u_cm_np1_ba_med_6.avi ', but some of others can  be opened by av.open(), this is weird :), my version o av is 8.0.2

**Comment by AllenPu** [comment]
I also tried the av==9.2.0 but it shows: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 65: invalid start byte for the video :  WeTheKingsplaying_shoot_ball_u_cm_np1_ri_med_1.avi

**Comment by kahnchana** [comment]
If only some videos can't be opened, maybe it's an issue with the videos? I'm not getting that error when I run the code, so I can't seem to debug this. My AV version is also 9.2.0

**Comment by AllenPu** [comment]
I still have the problem when run the code \:
container = av.open(''/HMDB51/videos/shoot_ball/WeTheKingsplaying_shoot_ball_u_cm_np1_ba_med_6.avi')
I have no idea why this happens, maybe I should try to download the dataset again?

**Comment by kahnchana** [comment]
Did this issue get resolved?
